backend:
  name: git-gateway
  # name: test-repo
  # repo: hendhyhutomo/gatsbyv2

media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: 'issetting', label: 'issetting', widget: 'hidden', default: 'true', required: true, }
      - { name: 'contenttype', label: 'contenttype', widget: 'hidden', default: 'blog', required: true, }
      - {
          name: 'slug',
          label: 'Slug',
          widget: 'string',
          pattern:
            [
              '([a-z0-9]){3,}',
              'Lowercase and Numerical Only, Minimum Characters = 3',
            ],
        }
      - { name: 'index', label: 'Index', widget: 'number', default: 0, }
      - { name: 'date', label: 'Date', widget: 'date', }
      - { name: 'title', label: 'Title', }
      - { name: 'coverimage', label: 'Cover Image', widget: 'image', }
      - { name: 'body', label: 'Body', widget: 'markdown', }
  - label: 'Settings'
    name: 'settings'
    extension: 'md'
    delete: false
    editor:
      preview: false
    files:
      - file: 'src/settings/general.md'
        label: 'General Setting'
        name: 'general'
        identifier_field: title
        delete: false
        description: 'General Site Settings'
        fields:
          - { name: 'issetting', label: 'issetting', widget: 'hidden', default: true, required: true, }
          - { name: 'contenttype', label: 'contenttype', widget: 'hidden', default: 'general_setting', required: true, }
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'General Setting', required: true, }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/settings/slug.md'
        label: 'URL Redirect'
        name: 'slug'
        identifier_field: title
        delete: false
        description: 'Creates URL Redirector'
        fields:
          - { name: 'issetting', label: 'issetting', widget: 'hidden', default: true, required: true, }
          - { name: 'contenttype', label: 'contenttype', widget: 'hidden', default: 'slug_setting', required: true, }
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'URL Redirect', required: true, }
          - name: 'redirect'
            label: 'URL LIST'
            widget: 'list'
            label_singular: 'Redirect'
            required: false
            hint: 'EG: from "/google" to "https://google.com" set active "on"'
            fields:
              - { label: 'From', name: 'from', widget: 'string', pattern: [ '([a-z0-9]){3,}', 'Lowercase and Numerical Only, Minimum Characters = 3',] }
              - { label: 'To', name: 'to', widget: 'string' }
              - { label: 'Active', name: 'status', widget: 'boolean', default: false }
