backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets
collections:
  - label: 'Settings'
    name: 'settings'
    delete: false
    editor:
      preview: false
    files:
      - file: 'src/settings/general.md'
        label: 'General Setting'
        name: 'general'
        delete: false
        description: 'General Site Settings'
        fields:
          - { name: 'issetting', label: 'issetting', widget: 'hidden', default: true, required: true, }
          - { name: 'contenttype', label: 'contenttype', widget: 'hidden', default: 'general_setting', required: true, }
          - { label: 'Website Title', name: 'title', widget: 'string', required: true, }
          - label: "META INFO"
            name: "seo"
            widget: "object"
            fields:
            - { label: 'Short Description', name: 'seo_shortdesc', widget: 'string', hint: 'Max (200 Characters).', required: true }
            - { label: 'Keywords', name: 'seo_keywords', widget: 'string',  hint: 'Each Keywords are seperated with a comma (","). Max (200 Characters).', required: true }
            - { name: 'seo_image', label: 'Image', widget: 'image', hint: 'width: 1200px, height: 600px', required: true}
          - { name: 'bg_img', label: 'Background Image', widget: 'image', allow_multiple: true, required: true} 
          - label: "Works"
            name: "work"
            widget: "object"
            fields:
            - { label: 'Work Link', name: 'link', widget: 'string', required: true }
            - { label: 'Show File', name: 'toggle', widget: 'boolean',  default: false, required: true }
            - { label: 'Work File', name: 'file', widget: 'file', required: false, allow_multiple: false}
          - { label: 'Email Address', name: 'title', widget: 'string', required: true, }
          - { label: 'About', name: 'body', widget: 'markdown' }