backend:
  name: git-gateway
  # name: test-repo
  # repo: hendhyhutomo/gatsbyv2

media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: "issetting", label: "issetting", widget: "hidden", default: "true", required: true}
      - {
          name: "slug",
          label: "Slug",
          widget: "string",
          pattern:
            [
              "([a-z0-9]){3,}",
              "Lowercase and Numerical Only, Minimum Characters = 3",
            ],
        }
      - { name: "index", label: "Index", widget: "number", default: 0 }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "title", label: "Title" }
      - { name: "coverimage", label: "Cover Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "General Setting"
        name: "general"
        file: "src/settings/general.md"
        identifier_field: title
        fields:
          - { label: "Intro", name: "intro", widget: "markdown" }
          - { label: Title, name: "title", widget: "hidden", default: "General Setting", required: true}
          - { name: "_issetting", label: "issetting", widget: "hidden", default: true, required: true }
          - { name: "_contenttype", label: "contenttype", widget: "hidden", default: "general_setting", required: true }
      - label: "URL Redirect"
        name: "slug"
        file: "src/settings/slug.md"
        identifier_field: title
        fields:
          - label: "Redirect"
            name: "redirect"
            widget: "list"
            required: false
            hint: "EG: from '/google' to 'https://google.com' set active 'on'"
            fields:
              - { label: "From", name: "name", widget: "string", pattern: [ "([a-z0-9]){3,}", "Lowercase and Numerical Only, Minimum Characters = 3",] }
              - { label: "To", name: "address", widget: "string" }
              - { label: "Active", name: "status", widget: "boolean", default: false }
          - { name: "issetting", label: "issetting", widget: "hidden", default: true, required: true }
          - { name: "contenttype", label: "contenttype", widget: "hidden", default: "slug_setting", required: true }
          - { label: "Title", name: "title", widget: "hidden", default: "URL Redirect", required: true}
