backend:
  # name: test-repo
  name: git-gateway
  # repo: hendhyhutomo/gatsbyv2

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: "coverimage", label: "Cover Image", widget: "image"}
      - { name: body, label: Body, widget: markdown }
